# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 08:02
from __future__ import unicode_literals

import blog1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_auto_20181221_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog1.models.upload_location),
        ),
    ]
